name: Selenium Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      test_scenario:
        description: 'Scénario de test à exécuter'
        required: false
        default: 'all'
        type: choice
        options:
        - all
        - login.test.js
        - register.test.js
        - project.test.js
        - projectDetails.test.js
        - company.test.js
        - employee.test.js 
        - juridique.test.js
        - document.test.js

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install browser
      uses: browser-actions/setup-chrome@latest
    
    - name: Run Selenium tests
      run: |
        if [ "${{ github.event.inputs.test_scenario }}" = "all" ] || [ "${{ github.event.inputs.test_scenario }}" = "" ]; then
          npm test
        else
          # Adaptez cette commande en fonction de comment vous souhaitez exécuter des scénarios spécifiques
          npm test -- --file ${{ github.event.inputs.test_scenario }}
        fi